steps:
  - name: 'gcr.io/cloud-builders/mvn'
  - args:
      - "-DskipTests"
      - "package"
      - "com.google.cloud.tools:jib-maven-plugin:build"
      - "-Dimage=gcr.io/$PROJECT_ID/hello-java:v1"