apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-java-deployment
spec:
  selector:
    matchLabels:
      app: hello-java
  template:
    metadata:
      labels:
        app: hello-java
    spec:
      containers:
      - name: hello-java
        image: gcr.io/my-kubernetes-codelab-336610/hello-java:v1
        resources:
          requests:
            memory: "32Mi"
            cpu: "100m"
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 8080
